<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0ku6YNR\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0ku6YNR/appAppKernelProdContainer.php') {
    touch(__DIR__.'/Container0ku6YNR.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\Container0ku6YNR\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \Container0ku6YNR\appAppKernelProdContainer([
    'container.build_hash' => '0ku6YNR',
    'container.build_id' => '92d885db',
    'container.build_time' => 1720711303,
], __DIR__.\DIRECTORY_SEPARATOR.'Container0ku6YNR');
