<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.JM.9EzS' shared service.

return $this->privates['.service_locator.JM.9EzS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'filters' => ['privates', '.errored..service_locator.JM.9EzS.PrestaShop\\PrestaShop\\Core\\Search\\Filters\\ProductCombinationFilters', NULL, 'Cannot autowire service ".service_locator.JM.9EzS": it references class "PrestaShop\\PrestaShop\\Core\\Search\\Filters\\ProductCombinationFilters" but no such service exists.'],
], [
    'filters' => 'PrestaShop\\PrestaShop\\Core\\Search\\Filters\\ProductCombinationFilters',
]);
