<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PrestaShop\Module\PsxMarketingWithGoogle\ProductFilter\Options\BrandOptionsProvider' shared service.

return $this->services['PrestaShop\\Module\\PsxMarketingWithGoogle\\ProductFilter\\Options\\BrandOptionsProvider'] = new \PrestaShop\Module\PsxMarketingWithGoogle\ProductFilter\Options\BrandOptionsProvider(($this->services['PrestaShop\\Module\\PsxMarketingWithGoogle\\Repository\\ManufacturerRepository'] ?? $this->load('getManufacturerRepository2Service.php')));
