<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mbo.hook_exception_holder' shared service.

return $this->services['mbo.hook_exception_holder'] = new \PrestaShop\Module\Mbo\Service\HookExceptionHolder();
