<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'ps_eventbus.module.upgrade' shared service.

return $this->services['ps_eventbus.module.upgrade'] = new \PrestaShop\Module\PsEventbus\Module\Upgrade(($this->services['ps_eventbus'] ?? $this->load('getPsEventbusService.php')));
