<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.module.psxdesign.validator.features_compatibility_validator' shared service.

return $this->services['prestashop.module.psxdesign.validator.features_compatibility_validator'] = new \PrestaShop\Module\PsxDesign\Validator\FeaturesCompatibilityValidator(($this->services['prestashop.core.addon.theme.theme_provider'] ?? $this->load('getPrestashop_Core_Addon_Theme_ThemeProviderService.php'))->getCurrentlyUsedTheme());
