<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.module.psxdesign.utility.theme_configuration.color_utility' shared service.

return $this->services['prestashop.module.psxdesign.utility.theme_configuration.color_utility'] = new \PrestaShop\Module\PsxDesign\Utility\ThemeConfiguration\ColorUtility(($this->services['psxdesign.module'] ?? $this->load('getPsxdesign_ModuleService.php'))->getTranslator());
