<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.module.psxdesign.provider.global_theme_configuration_provider' shared service.

return $this->services['prestashop.module.psxdesign.provider.global_theme_configuration_provider'] = new \PrestaShop\Module\PsxDesign\Provider\ThemeConfiguration\GlobalConfigurationProvider(($this->services['PrestaShop\\PrestaShop\\Adapter\\LegacyContext'] ?? $this->getLegacyContextService())->getContext()->shop->id);
