<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.module.psxdesign.handler.color_stylesheet_updater' shared service.

return $this->services['prestashop.module.psxdesign.handler.color_stylesheet_updater'] = new \PrestaShop\Module\PsxDesign\Handler\ColorsStylesheetUpdater(($this->services['prestashop.module.psxdesign.provider.theme_configuration_provider'] ?? $this->load('getPrestashop_Module_Psxdesign_Provider_ThemeConfigurationProviderService.php')), ($this->services['psxdesign.module'] ?? $this->load('getPsxdesign_ModuleService.php'))->getLocalPath(), ($this->services['filesystem'] ?? ($this->services['filesystem'] = new \Symfony\Component\Filesystem\Filesystem())), ($this->services['prestashop.module.psxdesign.processor.colors_stylesheet_processor'] ?? $this->load('getPrestashop_Module_Psxdesign_Processor_ColorsStylesheetProcessorService.php')));
