<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.module.psxdesign.account.provider.token_decoder' shared service.

return $this->services['prestashop.module.psxdesign.account.provider.token_decoder'] = new \PrestaShop\Module\PsxDesign\Account\Provider\TokenDecoder(($this->services['prestashop.module.psxdesign.token_parser'] ?? ($this->services['prestashop.module.psxdesign.token_parser'] = new \Lcobucci\JWT\Parser())));
