<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.module.psxdesign.processor.font_stylesheets_processor' shared service.

return $this->services['prestashop.module.psxdesign.processor.font_stylesheets_processor'] = new \PrestaShop\Module\PsxDesign\Processor\FontStylesheetsProcessor(($this->services['filesystem'] ?? ($this->services['filesystem'] = new \Symfony\Component\Filesystem\Filesystem())), ($this->services['prestashop.module.psxdesign.provider.theme_configuration_provider'] ?? $this->load('getPrestashop_Module_Psxdesign_Provider_ThemeConfigurationProviderService.php')), ($this->services['prestashop.module.psxdesign.repository.psxdesign_fonts_repository'] ?? $this->load('getPrestashop_Module_Psxdesign_Repository_PsxdesignFontsRepositoryService.php')), ($this->services['prestashop.module.psxdesign.builder.fonts_stylesheet_builder'] ?? $this->load('getPrestashop_Module_Psxdesign_Builder_FontsStylesheetBuilderService.php')), ($this->services['prestashop.module.psxdesign.utility.theme_configuration.font_utility'] ?? $this->load('getPrestashop_Module_Psxdesign_Utility_ThemeConfiguration_FontUtilityService.php')), ($this->services['psxdesign.module'] ?? $this->load('getPsxdesign_ModuleService.php'))->getLocalPath(), ($this->services['PrestaShop\\PrestaShop\\Adapter\\LegacyContext'] ?? $this->getLegacyContextService())->getContext()->shop->id);
