<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.module.psxdesign.provider.theme_image_provider' shared service.

return $this->services['prestashop.module.psxdesign.provider.theme_image_provider'] = new \PrestaShop\Module\PsxDesign\Provider\ThemeImagesProvider((\dirname(__DIR__, 4).'/themes/'));
