<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.module.psxdesign.builder.colors_stylesheet_builder' shared service.

return $this->services['prestashop.module.psxdesign.builder.colors_stylesheet_builder'] = new \PrestaShop\Module\PsxDesign\Builder\ColorsStylesheetBuilder();
