<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mbo.modules.transitions_manager' shared service.

return $this->services['mbo.modules.transitions_manager'] = new \PrestaShop\Module\Mbo\Module\Workflow\TransitionsManager(($this->services['prestashop.module.manager'] ?? $this->load('getPrestashop_Module_ManagerService.php')), ($this->services['mbo.hook_exception_holder'] ?? ($this->services['mbo.hook_exception_holder'] = new \PrestaShop\Module\Mbo\Service\HookExceptionHolder())));
