<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mbo.modules.transition_builder' shared service.

return $this->services['mbo.modules.transition_builder'] = new \PrestaShop\Module\Mbo\Module\Workflow\TransitionBuilder();
