<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.module.psxdesign.handler.color_palette_upsert_handler' shared service.

return $this->services['prestashop.module.psxdesign.handler.color_palette_upsert_handler'] = new \PrestaShop\Module\PsxDesign\Handler\ColorPaletteUpsertHandler(($this->services['prestashop.module.psxdesign.validator.color_palette_validator'] ?? ($this->services['prestashop.module.psxdesign.validator.color_palette_validator'] = new \PrestaShop\Module\PsxDesign\Validator\ColorPaletteValidator())), ($this->services['prestashop.module.psxdesign.repository.psxdesign_color_repository'] ?? $this->load('getPrestashop_Module_Psxdesign_Repository_PsxdesignColorRepositoryService.php')), ($this->services['prestashop.module.psxdesign.repository.psxdesign_colors_palette_repository'] ?? $this->load('getPrestashop_Module_Psxdesign_Repository_PsxdesignColorsPaletteRepositoryService.php')), ($this->services['prestashop.module.psxdesign.processor.colors_stylesheet_processor'] ?? $this->load('getPrestashop_Module_Psxdesign_Processor_ColorsStylesheetProcessorService.php')), ($this->services['prestashop.module.psxdesign.builder.color_palette_builder'] ?? $this->load('getPrestashop_Module_Psxdesign_Builder_ColorPaletteBuilderService.php')), ($this->services['prestashop.module.psxdesign.provider.theme_configuration_provider'] ?? $this->load('getPrestashop_Module_Psxdesign_Provider_ThemeConfigurationProviderService.php')), ($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService()));
