<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.module.psxdesign.compiler.theme_stylesheet_compiler' shared service.

return $this->services['prestashop.module.psxdesign.compiler.theme_stylesheet_compiler'] = new \PrestaShop\Module\PsxDesign\Compiler\ThemeStylesheetCompiler(($this->services['psxdesign.module'] ?? $this->load('getPsxdesign_ModuleService.php'))->getLocalPath(), (\dirname(__DIR__, 4).'/themes/'), ($this->services['filesystem'] ?? ($this->services['filesystem'] = new \Symfony\Component\Filesystem\Filesystem())), ($this->services['prestashop.module.psxdesign.provider.theme_configuration_provider'] ?? $this->load('getPrestashop_Module_Psxdesign_Provider_ThemeConfigurationProviderService.php')), ($this->services['PrestaShop\\PrestaShop\\Adapter\\LegacyContext'] ?? $this->getLegacyContextService())->getContext()->shop->id);
