<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.module.psxdesign.repository.psxdesign_color_repository' shared service.

return $this->services['prestashop.module.psxdesign.repository.psxdesign_color_repository'] = new \PrestaShop\Module\PsxDesign\Repository\PsxdesignColorRepository(($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService()));
