<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.module.psxdesign.validator.color_palette_validator' shared service.

return $this->services['prestashop.module.psxdesign.validator.color_palette_validator'] = new \PrestaShop\Module\PsxDesign\Validator\ColorPaletteValidator();
