<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.module.psxdesign.tracker.segment' shared service.

return $this->services['prestashop.module.psxdesign.tracker.segment'] = new \PrestaShop\Module\PsxDesign\Tracker\SegmentTracker(($this->services['psxdesign.accounts.data_provider'] ?? $this->load('getPsxdesign_Accounts_DataProviderService.php')), ($this->services['psxdesign.context'] ?? $this->load('getPsxdesign_ContextService.php')), ($this->services['prestashop.module.psxdesign.account.provider.token_decoder'] ?? $this->load('getPrestashop_Module_Psxdesign_Account_Provider_TokenDecoderService.php')), $this->getEnv('PSXDESIGN_SEGMENT_PHP'), ($this->services['psxdesign.module'] ?? $this->load('getPsxdesign_ModuleService.php'))->version, ($this->services['psxdesign.module'] ?? $this->load('getPsxdesign_ModuleService.php'))->name, ($this->services['prestashop.core.addon.theme.theme_provider'] ?? $this->load('getPrestashop_Core_Addon_Theme_ThemeProviderService.php'))->getCurrentlyUsedTheme()->getName());
