<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PrestaShop\Module\PsEventbus\Api\SyncApiClient' shared service.

return $this->services['PrestaShop\\Module\\PsEventbus\\Api\\SyncApiClient'] = new \PrestaShop\Module\PsEventbus\Api\SyncApiClient('https://eventbus-sync.psessentials.net', ($this->services['ps_eventbus'] ?? $this->load('getPsEventbusService.php')), ($this->services['PrestaShop\\Module\\PsEventbus\\Service\\PsAccountsAdapterService'] ?? $this->load('getPsAccountsAdapterServiceService.php')));
