<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.yPfykcG' shared service.

return $this->privates['.service_locator.yPfykcG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'form' => ['privates', '.errored..service_locator.yPfykcG.Symfony\\Component\\Form\\FormInterface', NULL, 'Cannot autowire service ".service_locator.yPfykcG": it references interface "Symfony\\Component\\Form\\FormInterface" but no such service exists. Did you create a class that implements this interface?'],
], [
    'form' => 'Symfony\\Component\\Form\\FormInterface',
]);
