<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.module.psxdesign.exception.handler.sentry_exception_error_handler' shared service.

return $this->services['prestashop.module.psxdesign.exception.handler.sentry_exception_error_handler'] = new \PrestaShop\Module\PsxDesign\Exception\Handler\SentryExceptionErrorHandler(($this->services['psxdesign.accounts.data_provider'] ?? $this->load('getPsxdesign_Accounts_DataProviderService.php')), ($this->services['prestashop.module.manager'] ?? $this->load('getPrestashop_Module_ManagerService.php')), $this->getEnv('PSXDESIGN_SENTRY_DSN'), $this->getEnv('PSXDESIGN_SENTRY_ENV'), ($this->services['psxdesign.module'] ?? $this->load('getPsxdesign_ModuleService.php'))->name, ($this->services['psxdesign.module'] ?? $this->load('getPsxdesign_ModuleService.php'))->version);
