<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'psxdesign.accounts.data_provider' shared service.

return $this->services['psxdesign.accounts.data_provider'] = new \PrestaShop\Module\PsxDesign\Account\Provider\PsAccountDataProvider(($this->services['psxdesign.ps_accounts.facade'] ?? $this->load('getPsxdesign_PsAccounts_FacadeService.php')));
