<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'ps_eventbus.service.presenter' shared service.

return $this->services['ps_eventbus.service.presenter'] = new \PrestaShop\Module\PsEventbus\Service\PresenterService();
