<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'ps_billings.facade' shared service.

return $this->services['ps_billings.facade'] = new \PrestaShopCorp\Billing\Presenter\BillingPresenter(($this->services['ps_billings.context_wrapper'] ?? $this->load('getPsBillings_ContextWrapperService.php')), (($this->get("smb_edition.module")) ? ($this->get("smb_edition.module")) : (null)));
