<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.module.psxdesign.builder.color_palette_builder' shared service.

return $this->services['prestashop.module.psxdesign.builder.color_palette_builder'] = new \PrestaShop\Module\PsxDesign\Builder\ColorPaletteBuilder(($this->services['prestashop.module.psxdesign.provider.theme_configuration_provider'] ?? $this->load('getPrestashop_Module_Psxdesign_Provider_ThemeConfigurationProviderService.php')), ($this->services['prestashop.core.addon.theme.theme_provider'] ?? $this->load('getPrestashop_Core_Addon_Theme_ThemeProviderService.php'))->getCurrentlyUsedTheme()->getName());
