<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.order.order_detail.updater' shared service.

return $this->services['prestashop.adapter.order.order_detail.updater'] = new \PrestaShop\PrestaShop\Adapter\Order\OrderDetailUpdater(($this->services['PrestaShop\\PrestaShop\\Adapter\\ContextStateManager'] ?? $this->load('getContextStateManager2Service.php')), ($this->services['PrestaShop\\PrestaShop\\Adapter\\Configuration'] ?? ($this->services['PrestaShop\\PrestaShop\\Adapter\\Configuration'] = new \PrestaShop\PrestaShop\Adapter\Configuration())));
