<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.module.psxdesign.provider.theme_attributes_provider' shared service.

return $this->services['prestashop.module.psxdesign.provider.theme_attributes_provider'] = new \PrestaShop\Module\PsxDesign\Provider\ThemeAttributesProvider(($this->services['prestashop.core.addon.theme.theme_provider'] ?? $this->load('getPrestashop_Core_Addon_Theme_ThemeProviderService.php')), ($this->services['prestashop.module.psxdesign.provider.theme_image_provider'] ?? ($this->services['prestashop.module.psxdesign.provider.theme_image_provider'] = new \PrestaShop\Module\PsxDesign\Provider\ThemeImagesProvider((\dirname(__DIR__, 4).'/themes/')))), ($this->services['prestashop.core.addon.theme.repository'] ?? $this->load('getPrestashop_Core_Addon_Theme_RepositoryService.php')), ($this->services['psxdesign.context'] ?? $this->load('getPsxdesign_ContextService.php'))->link, ($this->services['prestashop.module.psxdesign.provider.theme_configuration_provider'] ?? $this->load('getPrestashop_Module_Psxdesign_Provider_ThemeConfigurationProviderService.php')));
